# Generated by Django 6.1 on 2026-09-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
        migrations.AddField(
            model_name='project',
            name='approach',
            field=models.TextField(blank=True, help_text='How the solution was conceived and designed.', null=True, verbose_name='Approach'),
        ),
        migrations.AddField(
            model_name='project',
            name='context',
            field=models.TextField(blank=True, help_text='The situation or background before the project.', null=True, verbose_name='Context'),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, help_text='Important features of the solution.', null=True, verbose_name='Key Features'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, help_text='What was not working or what needed to change.', null=True, verbose_name='Problem'),
        ),
        migrations.AddField(
            model_name='project',
            name='result',
            field=models.TextField(blank=True, help_text='The outcome and impact for the client.', null=True, verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.TextField(blank=True, help_text='What I specifically did on this project.', null=True, verbose_name='My Role'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, help_text='What was built and how it works.', null=True, verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress')], default='completed', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.technology', verbose_name='Technologies'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
