# Generated by Django 6.1 on 2026-09-03 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_article_author_remove_article_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='audience',
            field=models.TextField(blank=True, help_text='Who benefits from this solution.', verbose_name='Audience'),
        ),
        migrations.AddField(
            model_name='service',
            name='before_after',
            field=models.TextField(blank=True, help_text='The transformation this solution enables.', verbose_name='Before / After'),
        ),
        migrations.AddField(
            model_name='service',
            name='benefits',
            field=models.TextField(blank=True, help_text='What the client gains.', verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='service',
            name='concrete_example',
            field=models.TextField(blank=True, help_text='A concrete example to help the prospect visualize.', verbose_name='Concrete Example'),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.TextField(blank=True, help_text='What can be built — explained in simple terms.', verbose_name='Features'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_description',
            field=models.TextField(blank=True, help_text='The main proposition shown at the top of the detail page.', verbose_name='Hero Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='how_it_works',
            field=models.TextField(blank=True, help_text='Step-by-step explanation of how the solution works.', verbose_name='How It Works'),
        ),
        migrations.AddField(
            model_name='service',
            name='included',
            field=models.TextField(blank=True, help_text='Scope of the solution.', verbose_name="What's Included"),
        ),
        migrations.AddField(
            model_name='service',
            name='problem',
            field=models.TextField(blank=True, help_text='Why this solution exists — the problem it solves.', verbose_name='Problem'),
        ),
        migrations.AddField(
            model_name='service',
            name='technical_details',
            field=models.TextField(blank=True, help_text='Secondary technical information for interested visitors.', verbose_name='Technical Details'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_items', to='portfolio.service', verbose_name='Service'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('organization', models.CharField(max_length=200, verbose_name='Organization')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Is Current')),
                ('type', models.CharField(choices=[('professional', 'Professional'), ('freelance', 'Freelance'), ('academic', 'Academic'), ('personal', 'Personal')], default='professional', max_length=20, verbose_name='Type')),
                ('role', models.TextField(blank=True, help_text='What was my role in this position.', verbose_name='Role')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities in this role.', verbose_name='Responsibilities')),
                ('tasks', models.TextField(blank=True, help_text='Concrete tasks performed.', verbose_name='Tasks')),
                ('achievements', models.TextField(blank=True, help_text='What was accomplished.', verbose_name='Achievements')),
                ('results', models.TextField(blank=True, help_text='Impact and results when available.', verbose_name='Results')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('related_projects', models.ManyToManyField(blank=True, related_name='experiences', to='portfolio.project', verbose_name='Related Projects')),
                ('technologies', models.ManyToManyField(blank=True, related_name='experiences', to='portfolio.technology', verbose_name='Technologies')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
