# Generated by Django 6.1 on 2026-09-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_service_audience_service_before_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('icon', models.CharField(help_text='Font Awesome icon class (e.g., fa-python, fa-react)', max_length=50, verbose_name='Icon Class')),
                ('category', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('database', 'Database'), ('tool', 'Tool'), ('other', 'Other')], default='tool', max_length=20, verbose_name='Category')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
