# Generated by Django 6.1 on 2026-09-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='services', to='portfolio.project', verbose_name='Related Projects'),
        ),
    ]
